[project]
name = "pydantic-ai-chat"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.117.1",
    "logfire[fastapi,starlette]>=4.9.0",
    "pydantic-ai-slim[anthropic,cli,google,openai]>=1.14.0",
    "sse-starlette>=3.0.2",
    "starlette>=0.48.0",
    "uvicorn>=0.37.0",
]

[dependency-groups]
dev = [
    "pyright>=1.1.405",
    "watchfiles>=1.1.0",
]

[tool.ruff.format]
# don't format python in docstrings, pytest-examples takes care of it
docstring-code-format = false
quote-style = "single"
